### ISSUE TITLE
Seconds are returned incorrectly.

### ISSUE THREAD

**Issue by JChristensen** [adafruit/Adafruit_CircuitPython_DS1307#1]
[Line 271](https://github.com/adafruit/Adafruit_MicroPython_DS1307/blob/master/adafruit_ds1307.py#L271) should be:
`second=_bcd2bin(buffer[0] & 0x7F),`

**Comment by tannewt** [comment]
Thanks for the bug report! I've fixed the issue by switching to the [Register library](https://github.com/adafruit/Adafruit_CircuitPython_Register) which is shared between all of the RTC drivers in 2bc9b5f8498860ce2ec62719383483f04ea48119.
