### ISSUE TITLE
Example day-of-week string indexing is off-by-one in many repos

### ISSUE THREAD

**Issue by mew-cx** [adafruit/Adafruit_CircuitPython_DS1307#26]
In [examples/ds1307_simpletest.py](https://github.com/adafruit/Adafruit_CircuitPython_DS1307/blob/main/examples/ds1307_simpletest.py#L17), the list of strings used to expand the integer `time.struct_time.tm_wday` value appears to defined using the C convention (Sunday=0), rather than the Python convention (Monday=0); see https://docs.python.org/3/library/time.html#time.struct_time

A quick search reveals this error in several other repos:
- https://github.com/adafruit/Adafruit_CircuitPython_PCF8563/blob/main/examples/pcf8563_simpletest.py#L24
- https://github.com/adafruit/Adafruit_CircuitPython_PCF8523/blob/main/examples/pcf8523_simpletest.py#L17
- https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/main/Pulse_Oximeter_Logger/code.py#L46
- https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/main/blahaj/code.py#L22
- https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/main/Disconnected_CO2_Data_Logger/code.py#L23
- https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/main/Pulse_Oximeter_Logger/code.py#L46
- https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/main/Daily_Cheer_Automaton/CircuitPython/code.py#L121
- https://github.com/adafruit/Adafruit_Learning_System_Guides/blob/main/MagTag_Google_Sheets/weekly_planner/code.py#L25
- perhaps others?

**Comment by FoamyGuy** [comment]
For now I think we can leave this one open until we take care of the rest of the instances in this list, or create separate issues on those repos

**Comment by FoamyGuy** [comment]
@tekktrik okay, sounds good. I'm working on the change for the PCF ones now.

**Comment by mew-cx** [comment]
Yeah, figured I'd leave it to yall to decide how best to distribute the issues among repos.  Thanks for taking it over
